apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::008089408493:role/eks_iam_role_dummy
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  serviceAccountName: dummy
  containers:
    - name: dummy
      image: amazon/aws-cli
      command: [ "tail", "-f", "/dev/null" ]