apiVersion: v1
kind: Pod
metadata:
  name: storage-demo
spec:
  containers:
    - name: con1
      image: centos
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - mountPath: /parameters
          name: tmp
    - name: con2
      image: centos
      command: ["tail", "-f", "/dev/null"]
      volumeMounts: /parameters
      name: tmp
  volumes:
    - name: tmp
      emptyDir:
        sizeLimit: 5Mi