apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: 008089408493.dkr.ecr.us-east-1.amazonaws.com/frontend:2.0.1
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: backend
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: mysql
#spec:
#  containers:
#    - name: nginx
#      image: nginx
